import random
WINDOW_W, WINDOW_H = 800, 600
CELL = 20
COLS, ROWS = WINDOW_W // CELL, WINDOW_H // CELL  # 40 x 30
FPS = 60
MAX_FRAMES_PER_EPISODE = 600
SQUARE_SIZE = 14
SQUARE_SPEED = 2.0
CHASE_RADIUS = 10
EVAL_OPPONENTS_PER_INDIVIDUAL = 5
POP_SIZE = 50
NUM_MAZES = 3
GLOBAL_RNG = random.Random()  # 由 main.py 用 --seed 初始化，默认随机
